[{"Id" : "a005g00002zqOGwAAM", "Name" : "SomeName1", "Connected_Org_Record_Id__c": "a005g00002zqOGwAAW"},
{"Id" : "a005g00002zpbiwAAA", "Name" : "SomeName2", "Connected_Org_Record_Id__c": "a005g00002zpbiwAAW"},
{"Id" : "a005g00002zpucjAAA", "Name" : "SomeName3", "Connected_Org_Record_Id__c": "a005g00002zpucjAAW"},
{"Id" : "a005g00002zpQDlAAM", "Name" : "SomeName4", "Connected_Org_Record_Id__c": "a005g00002zpQDlAAW"},
{"Id" : "a005g00003102fVAAQ", "Name" : "SomeName5", "Connected_Org_Record_Id__c": "a005g00003102fVAAW"}]